name: CI | Test Handler

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  launch_runner_worker:
    runs-on: ubuntu-latest

    outputs:
      id: ${{ steps.extract_id.outputs.runpod_job_id }}

    steps:
      - name: Deploy Worker
        uses: fjogeleit/http-request-action@v1
        id: deploy
        with:
          url: "https://api.runpod.ai/v2/${{ vars.RUNNER_24GB }}/run"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.RUNPOD_API_TOKEN }}
          data: '{"input":{"github_pat": "${{ secrets.GH_PAT }}", "github_org":"${{ vars.GH_ORG }}"}}'

      - name: Extract Job ID
        id: extract_id
        run: |
          ID=$(echo '${{ steps.deploy.outputs.response }}' | jq -r '.id')
          echo "::set-output name=runpod_job_id::$ID"

  run_tests:
    needs: launch_runner_worker
    runs-on: runpod

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11 & install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y \
          libgl1-mesa-glx \
          libglib2.0-0

      - name: Install Python Dependencies
        env:
          PIP_ROOT_USER_ACTION: "ignore"
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt
          pip install pytest pytest-cov

      - name: Download Model
        run: |
          python -c "from diffusers import FluxPipeline; FluxPipeline.from_pretrained('black-forest-labs/FLUX.1-schnell')"

      - name: Execute Tests
        run: |
          python src/handler.py --test_input='{"input": {"prompt": "A test image of a cat", "height": 768, "width": 1360, "num_inference_steps": 4, "guidance_scale": 0.0, "max_sequence_length": 256}}'

  cleanup:
    if: ${{ always() && !success() }}
    needs: launch_runner_worker
    runs-on: ubuntu-latest

    steps:
      - name: Terminate and Shutdown Worker
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.runpod.ai/v2/${{ vars.RUNNER_24GB }}/cancel/${{ needs.launch_runner_worker.outputs.id }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.RUNPOD_API_TOKEN }}
